// AUTO-GENERATED: Skills registry from ~/.claude/skills/
// Last synced: 2026-03-14T21:43:37.741903

export interface Skill {
  id: string
  name: string
  description: string
  category: SkillCategory
  active: boolean
  lastUsed?: string
}

export type SkillCategory = 'empire' | 'content' | 'marketing' | 'business' | 'engineering' | 'ai' | 'video' | 'productivity' | 'product' | 'tools'

export const SKILLS_REGISTRY: Skill[] = [
  { id: "ab-test-setup", name: "ab-test-setup", description: "AI skill for ab test setup", category: "marketing", active: true },
  { id: "ad-creative", name: "ad-creative", description: "AI skill for ad creative", category: "marketing", active: true },
  { id: "agent-designer", name: "agent-designer", description: "AI skill for agent designer", category: "ai", active: true },
  { id: "agent-harness-construction", name: "agent-harness-construction", description: "Design and optimize AI agent action spaces, tool definitions, and observation formatting for higher completion rates.", category: "tools", active: true },
  { id: "agent-protocol", name: "agent-protocol", description: "AI skill for agent protocol", category: "tools", active: true },
  { id: "agent-workflow-designer", name: "agent-workflow-designer", description: "AI skill for agent workflow designer", category: "ai", active: true },
  { id: "agentic-engineering", name: "agentic-engineering", description: "Operate as an agentic engineer using eval-first execution, decomposition, and cost-aware model routing.", category: "ai", active: true },
  { id: "agile-product-owner", name: "agile-product-owner", description: "AI skill for agile product owner", category: "product", active: true },
  { id: "ai-first-engineering", name: "ai-first-engineering", description: "Engineering operating model for teams where AI agents generate a large share of implementation output.", category: "ai", active: true },
  { id: "ai-seo", name: "ai-seo", description: "AI skill for ai seo", category: "marketing", active: true },
  { id: "algorithmic-art", name: "algorithmic-art", description: "Creating algorithmic art using p5.js with seeded randomness and interactive parameter exploration. Use this when users request creating art using code, generative art, algorithmic art, flow fields, or", category: "tools", active: true },
  { id: "analytics-tracking", name: "analytics-tracking", description: "AI skill for analytics tracking", category: "tools", active: true },
  { id: "android-clean-architecture", name: "android-clean-architecture", description: "Clean Architecture patterns for Android and Kotlin Multiplatform projects \u2014 module structure, dependency rules, UseCases, Repositories, and data layer patterns.", category: "tools", active: true },
  { id: "api-design", name: "api-design", description: "REST API design patterns including resource naming, status codes, pagination, filtering, error responses, versioning, and rate limiting for production APIs.", category: "engineering", active: true },
  { id: "api-design-reviewer", name: "api-design-reviewer", description: "AI skill for api design reviewer", category: "tools", active: true },
  { id: "api-test-suite-builder", name: "api-test-suite-builder", description: "AI skill for api test suite builder", category: "tools", active: true },
  { id: "app-store-optimization", name: "app-store-optimization", description: "AI skill for app store optimization", category: "marketing", active: true },
  { id: "article-writing", name: "article-writing", description: "Write articles, guides, blog posts, tutorials, newsletter issues, and other long-form content in a distinctive voice derived from supplied examples or brand guidance. Use when the user wants polished ", category: "content", active: true },
  { id: "artifacts-builder", name: "artifacts-builder", description: "Suite of tools for creating elaborate, multi-component claude.ai HTML artifacts using modern frontend web technologies (React, Tailwind CSS, shadcn/ui). Use for complex artifacts requiring state manag", category: "ai", active: true },
  { id: "atlassian-admin", name: "atlassian-admin", description: "AI skill for atlassian admin", category: "tools", active: true },
  { id: "atlassian-templates", name: "atlassian-templates", description: "AI skill for atlassian templates", category: "tools", active: true },
  { id: "autonomous-loops", name: "autonomous-loops", description: "Patterns and architectures for autonomous Claude Code loops \u2014 from simple sequential pipelines to RFC-driven multi-agent DAG systems.", category: "ai", active: true },
  { id: "autoresearch-agent", name: "autoresearch-agent", description: "AI skill for autoresearch agent", category: "ai", active: true },
  { id: "aws-solution-architect", name: "aws-solution-architect", description: "AI skill for aws solution architect", category: "tools", active: true },
  { id: "backend-patterns", name: "backend-patterns", description: "Backend architecture patterns, API design, database optimization, and server-side best practices for Node.js, Express, and Next.js API routes.", category: "engineering", active: true },
  { id: "blueprint", name: "blueprint", description: "AI skill for blueprint", category: "tools", active: true },
  { id: "board-deck-builder", name: "board-deck-builder", description: "AI skill for board deck builder", category: "tools", active: true },
  { id: "board-meeting", name: "board-meeting", description: "AI skill for board meeting", category: "tools", active: true },
  { id: "board-prep", name: "board-prep", description: "AI skill for board prep", category: "tools", active: true },
  { id: "brand-guidelines", name: "brand-guidelines", description: "Applies Anthropic's official brand colors and typography to any sort of artifact that may benefit from having Anthropic's look-and-feel. Use it when brand colors or style guidelines, visual formatting", category: "empire", active: true },
  { id: "browserstack", name: "browserstack", description: "AI skill for browserstack", category: "tools", active: true },
  { id: "business-growth", name: "business-growth-skills", description: "4 production-ready business and growth skills: customer success manager with health scoring and churn prediction, sales engineer with RFP analysis, revenue operations with pipeline and GTM metrics, an", category: "business", active: true },
  { id: "business-growth-bundle", name: "business-growth-bundle", description: "AI skill for business growth bundle", category: "tools", active: true },
  { id: "c-level-advisor", name: "c-level-advisor", description: "Provides strategic business advice by channelling the perspectives of 10 executive roles \u2014 CEO, CTO, COO, CPO, CMO, CFO, CRO, CISO, CHRO, and Executive Mentor \u2014 across decisions, trade-offs, and org c", category: "tools", active: true },
  { id: "c-level-advisor-bundle", name: "c-level-advisor-bundle", description: "AI skill for c level advisor bundle", category: "tools", active: true },
  { id: "c-level-advisor-main", name: "c-level-advisor-main", description: "AI skill for c level advisor main", category: "tools", active: true },
  { id: "campaign-analytics", name: "campaign-analytics", description: "AI skill for campaign analytics", category: "marketing", active: true },
  { id: "canvas-design", name: "canvas-design", description: "Create beautiful visual art in .png and .pdf documents using design philosophy. You should use this skill when the user asks to create a poster, piece of art, design, or other static piece. Create ori", category: "tools", active: true },
  { id: "capa-officer", name: "capa-officer", description: "AI skill for capa officer", category: "tools", active: true },
  { id: "capture-screen", name: "capture-screen", description: "Programmatic screenshot capture on macOS. Find window IDs with Swift CGWindowListCopyWindowInfo, control application windows via AppleScript (zoom, scroll, select), and capture with screencapture. Use", category: "tools", active: true },
  { id: "carrier-relationship-management", name: "carrier-relationship-management", description: ">", category: "tools", active: true },
  { id: "ceo-advisor", name: "ceo-advisor", description: "AI skill for ceo advisor", category: "tools", active: true },
  { id: "cfo-advisor", name: "cfo-advisor", description: "AI skill for cfo advisor", category: "tools", active: true },
  { id: "challenge", name: "challenge", description: "AI skill for challenge", category: "tools", active: true },
  { id: "change-management", name: "change-management", description: "AI skill for change management", category: "tools", active: true },
  { id: "changelog", name: "changelog", description: "AI skill for changelog", category: "tools", active: true },
  { id: "changelog-generator", name: "changelog-generator", description: "Automatically creates user-facing changelogs from git commits by analyzing commit history, categorizing changes, and transforming technical commits into clear, customer-friendly release notes. Turns h", category: "tools", active: true },
  { id: "chief-of-staff", name: "chief-of-staff", description: "AI skill for chief of staff", category: "tools", active: true },
  { id: "chro-advisor", name: "chro-advisor", description: "AI skill for chro advisor", category: "tools", active: true },
  { id: "churn-prevention", name: "churn-prevention", description: "AI skill for churn prevention", category: "business", active: true },
  { id: "ci-cd-pipeline-builder", name: "ci-cd-pipeline-builder", description: "AI skill for ci cd pipeline builder", category: "engineering", active: true },
  { id: "ciso-advisor", name: "ciso-advisor", description: "AI skill for ciso advisor", category: "tools", active: true },
  { id: "claude-api", name: "claude-api", description: "Build apps with the Claude API or Anthropic SDK. TRIGGER when: code imports `anthropic`/`@anthropic-ai/sdk`/`claude_agent_sdk`, or user asks to use Claude API, Anthropic SDKs, or Agent SDK. DO NOT TRI", category: "tools", active: true },
  { id: "claude-code-history-files-finder", name: "claude-code-history-files-finder", description: "Finds and recovers content from Claude Code session history files. This skill should be used when searching for deleted files, tracking changes across sessions, analyzing conversation history, or reco", category: "tools", active: true },
  { id: "claude-export-txt-better", name: "fixing-claude-export-conversations", description: ">", category: "tools", active: true },
  { id: "claude-md-progressive-disclosurer", name: "claude-md-progressive-disclosurer", description: "|", category: "tools", active: true },
  { id: "claude-skills-troubleshooting", name: "claude-skills-troubleshooting", description: "Diagnose and resolve Claude Code plugin and skill issues. This skill should be used when plugins are installed but not showing in available skills list, skills are not activating as expected, or when ", category: "tools", active: true },
  { id: "cli-demo-generator", name: "cli-demo-generator", description: "This skill should be used when users want to create animated CLI demos, terminal recordings, or command-line demonstration GIFs. It supports both manual tape file creation and automated demo generatio", category: "tools", active: true },
  { id: "clickhouse-io", name: "clickhouse-io", description: "ClickHouse database patterns, query optimization, analytics, and data engineering best practices for high-performance analytical workloads.", category: "tools", active: true },
  { id: "client-acquisition", name: "client-acquisition", description: "Sales funnels, cold outreach, LinkedIn DM sequences, proposal-to-close pipeline, and client onboarding for FlipzyX AI automation agency.", category: "marketing", active: true },
  { id: "cloudflare-troubleshooting", name: "cloudflare-troubleshooting", description: "Investigate and resolve Cloudflare configuration issues using API-driven evidence gathering. Use when troubleshooting ERR_TOO_MANY_REDIRECTS, SSL errors, DNS issues, or any Cloudflare-related problems", category: "tools", active: true },
  { id: "cmo-advisor", name: "cmo-advisor", description: "AI skill for cmo advisor", category: "tools", active: true },
  { id: "code-review", name: "code-review", description: "Code review a pull request using 4 parallel agents \u2014 2 for CLAUDE.md compliance, 1 for bug detection, 1 for logic/security issues. Issues filtered at 80% confidence threshold. Use with /code-review <P", category: "engineering", active: true },
  { id: "code-reviewer", name: "code-reviewer", description: "AI skill for code reviewer", category: "engineering", active: true },
  { id: "codebase-onboarding", name: "codebase-onboarding", description: "AI skill for codebase onboarding", category: "tools", active: true },
  { id: "coding-standards", name: "coding-standards", description: "Universal coding standards, best practices, and patterns for TypeScript, JavaScript, React, and Node.js development.", category: "engineering", active: true },
  { id: "cold-email", name: "cold-email", description: "AI skill for cold email", category: "marketing", active: true },
  { id: "company-os", name: "company-os", description: "AI skill for company os", category: "tools", active: true },
  { id: "competitive-ads-extractor", name: "competitive-ads-extractor", description: "Extracts and analyzes competitors' ads from ad libraries (Facebook, LinkedIn, etc.) to understand what messaging, problems, and creative approaches are working. Helps inspire and improve your own ad c", category: "marketing", active: true },
  { id: "competitive-intel", name: "competitive-intel", description: "AI skill for competitive intel", category: "marketing", active: true },
  { id: "competitive-matrix", name: "competitive-matrix", description: "AI skill for competitive matrix", category: "marketing", active: true },
  { id: "competitive-teardown", name: "competitive-teardown", description: "AI skill for competitive teardown", category: "marketing", active: true },
  { id: "competitor-alternatives", name: "competitor-alternatives", description: "AI skill for competitor alternatives", category: "marketing", active: true },
  { id: "competitors-analysis", name: "competitors-analysis", description: "Analyze competitor repositories with evidence-based approach. Use when tracking competitors, creating competitor profiles, or generating competitive analysis. CRITICAL - all analysis must be based on ", category: "marketing", active: true },
  { id: "compose-multiplatform-patterns", name: "compose-multiplatform-patterns", description: "Compose Multiplatform and Jetpack Compose patterns for KMP projects \u2014 state management, navigation, theming, performance, and platform-specific UI.", category: "tools", active: true },
  { id: "configure-ecc", name: "configure-ecc", description: "Interactive installer for Everything Claude Code \u2014 guides users through selecting and installing skills and rules to user-level or project-level directories, verifies paths, and optionally optimizes i", category: "tools", active: true },
  { id: "confluence-expert", name: "confluence-expert", description: "AI skill for confluence expert", category: "tools", active: true },
  { id: "connect", name: "connect", description: "Connect Claude to any app. Send emails, create issues, post messages, update databases - take real actions across Gmail, Slack, GitHub, Notion, and 1000+ services.", category: "tools", active: true },
  { id: "connect-apps", name: "connect-apps", description: "Connect Claude to external apps like Gmail, Slack, GitHub. Use this skill when the user wants to send emails, create issues, post messages, or take actions in external services.", category: "tools", active: true },
  { id: "content-creator", name: "content-creator", description: "AI skill for content creator", category: "content", active: true },
  { id: "content-engine", name: "content-engine", description: "Create platform-native content systems for X, LinkedIn, TikTok, YouTube, newsletters, and repurposed multi-platform campaigns. Use when the user wants social posts, threads, scripts, content calendars", category: "content", active: true },
  { id: "content-hash-cache-pattern", name: "content-hash-cache-pattern", description: "Cache expensive file processing results using SHA-256 content hashes \u2014 path-independent, auto-invalidating, with service layer separation.", category: "tools", active: true },
  { id: "content-humanizer", name: "content-humanizer", description: "AI skill for content humanizer", category: "content", active: true },
  { id: "content-production", name: "content-production", description: "AI skill for content production", category: "content", active: true },
  { id: "content-research-writer", name: "content-research-writer", description: "Assists in writing high-quality content by conducting research, adding citations, improving hooks, iterating on outlines, and providing real-time feedback on each section. Transforms your writing proc", category: "content", active: true },
  { id: "content-strategy", name: "content-strategy", description: "AI skill for content strategy", category: "content", active: true },
  { id: "context-engine", name: "context-engine", description: "AI skill for context engine", category: "ai", active: true },
  { id: "context7", name: "context7", description: ">", category: "ai", active: true },
  { id: "continue-claude-work", name: "continue-claude-work", description: "Recover actionable context from local `.claude` session artifacts and continue interrupted work without running `claude --resume`. This skill should be used when the user provides a Claude session ID,", category: "tools", active: true },
  { id: "continuous-agent-loop", name: "continuous-agent-loop", description: "Patterns for continuous autonomous agent loops with quality gates, evals, and recovery controls.", category: "tools", active: true },
  { id: "continuous-learning", name: "continuous-learning", description: "Automatically extract reusable patterns from Claude Code sessions and save them as learned skills for future use.", category: "tools", active: true },
  { id: "continuous-learning-v2", name: "continuous-learning-v2", description: "Instinct-based learning system that observes sessions via hooks, creates atomic instincts with confidence scoring, and evolves them into skills/commands/agents. v2.1 adds project-scoped instincts to p", category: "tools", active: true },
  { id: "contract-and-proposal-writer", name: "contract-and-proposal-writer", description: "AI skill for contract and proposal writer", category: "business", active: true },
  { id: "coo-advisor", name: "coo-advisor", description: "AI skill for coo advisor", category: "tools", active: true },
  { id: "copy-editing", name: "copy-editing", description: "AI skill for copy editing", category: "content", active: true },
  { id: "copywriting", name: "copywriting", description: "AI skill for copywriting", category: "content", active: true },
  { id: "cost-aware-llm-pipeline", name: "cost-aware-llm-pipeline", description: "Cost optimization patterns for LLM API usage \u2014 model routing by task complexity, budget tracking, retry logic, and prompt caching.", category: "ai", active: true },
  { id: "coverage", name: "coverage", description: "AI skill for coverage", category: "engineering", active: true },
  { id: "cpo-advisor", name: "cpo-advisor", description: "AI skill for cpo advisor", category: "tools", active: true },
  { id: "cpp-coding-standards", name: "cpp-coding-standards", description: "C++ coding standards based on the C++ Core Guidelines (isocpp.github.io). Use when writing, reviewing, or refactoring C++ code to enforce modern, safe, and idiomatic practices.", category: "tools", active: true },
  { id: "cpp-testing", name: "cpp-testing", description: "Use only when writing/updating/fixing C++ tests, configuring GoogleTest/CTest, diagnosing failing or flaky tests, or adding coverage/sanitizers.", category: "tools", active: true },
  { id: "cro-advisor", name: "cro-advisor", description: "AI skill for cro advisor", category: "marketing", active: true },
  { id: "cs-agile-product-owner", name: "cs-agile-product-owner", description: "AI skill for cs agile product owner", category: "tools", active: true },
  { id: "cs-ceo-advisor", name: "cs-ceo-advisor", description: "AI skill for cs ceo advisor", category: "tools", active: true },
  { id: "cs-content-creator", name: "cs-content-creator", description: "AI skill for cs content creator", category: "tools", active: true },
  { id: "cs-cto-advisor", name: "cs-cto-advisor", description: "AI skill for cs cto advisor", category: "tools", active: true },
  { id: "cs-demand-gen-specialist", name: "cs-demand-gen-specialist", description: "AI skill for cs demand gen specialist", category: "tools", active: true },
  { id: "cs-engineering-lead", name: "cs-engineering-lead", description: "AI skill for cs engineering lead", category: "tools", active: true },
  { id: "cs-financial-analyst", name: "cs-financial-analyst", description: "AI skill for cs financial analyst", category: "tools", active: true },
  { id: "cs-growth-strategist", name: "cs-growth-strategist", description: "AI skill for cs growth strategist", category: "tools", active: true },
  { id: "cs-onboard", name: "cs-onboard", description: "AI skill for cs onboard", category: "tools", active: true },
  { id: "cs-product-analyst", name: "cs-product-analyst", description: "AI skill for cs product analyst", category: "tools", active: true },
  { id: "cs-product-manager", name: "cs-product-manager", description: "AI skill for cs product manager", category: "tools", active: true },
  { id: "cs-product-strategist", name: "cs-product-strategist", description: "AI skill for cs product strategist", category: "tools", active: true },
  { id: "cs-project-manager", name: "cs-project-manager", description: "AI skill for cs project manager", category: "tools", active: true },
  { id: "cs-quality-regulatory", name: "cs-quality-regulatory", description: "AI skill for cs quality regulatory", category: "tools", active: true },
  { id: "cs-senior-engineer", name: "cs-senior-engineer", description: "AI skill for cs senior engineer", category: "tools", active: true },
  { id: "cs-ux-researcher", name: "cs-ux-researcher", description: "AI skill for cs ux researcher", category: "tools", active: true },
  { id: "cs-workspace-admin", name: "cs-workspace-admin", description: "AI skill for cs workspace admin", category: "tools", active: true },
  { id: "cto-advisor", name: "cto-advisor", description: "AI skill for cto advisor", category: "tools", active: true },
  { id: "culture-architect", name: "culture-architect", description: "AI skill for culture architect", category: "tools", active: true },
  { id: "customer-success-manager", name: "customer-success-manager", description: "AI skill for customer success manager", category: "business", active: true },
  { id: "customs-trade-compliance", name: "customs-trade-compliance", description: ">", category: "tools", active: true },
  { id: "database-designer", name: "database-designer", description: "AI skill for database designer", category: "engineering", active: true },
  { id: "database-migrations", name: "database-migrations", description: "Database migration best practices for schema changes, data migrations, rollbacks, and zero-downtime deployments across PostgreSQL, MySQL, and common ORMs (Prisma, Drizzle, Django, TypeORM, golang-migr", category: "tools", active: true },
  { id: "database-schema-designer", name: "database-schema-designer", description: "AI skill for database schema designer", category: "tools", active: true },
  { id: "decision-frameworks", name: "decision-frameworks", description: "Mental models and decision tools for entrepreneurs \u2014 opportunity evaluation, prioritization matrices, risk assessment, and second-order thinking for $1M decisions.", category: "productivity", active: true },
  { id: "decision-logger", name: "decision-logger", description: "AI skill for decision logger", category: "productivity", active: true },
  { id: "deep-research", name: "deep-research", description: "|", category: "ai", active: true },
  { id: "dependency-auditor", name: "dependency-auditor", description: "AI skill for dependency auditor", category: "tools", active: true },
  { id: "deployment-patterns", name: "deployment-patterns", description: "Deployment workflows, CI/CD pipeline patterns, Docker containerization, health checks, rollback strategies, and production readiness checklists for web applications.", category: "engineering", active: true },
  { id: "developer-growth-analysis", name: "developer-growth-analysis", description: "Analyzes your recent Claude Code chat history to identify coding patterns, development gaps, and areas for improvement, curates relevant learning resources from HackerNews, and automatically sends a p", category: "tools", active: true },
  { id: "django-patterns", name: "django-patterns", description: "Django architecture patterns, REST API design with DRF, ORM best practices, caching, signals, middleware, and production-grade Django apps.", category: "tools", active: true },
  { id: "django-security", name: "django-security", description: "Django security best practices, authentication, authorization, CSRF protection, SQL injection prevention, XSS prevention, and secure deployment configurations.", category: "tools", active: true },
  { id: "django-tdd", name: "django-tdd", description: "Django testing strategies with pytest-django, TDD methodology, factory_boy, mocking, coverage, and testing Django REST Framework APIs.", category: "tools", active: true },
  { id: "django-verification", name: "django-verification", description: "Verification loop for Django projects: migrations, linting, tests with coverage, security scans, and deployment readiness checks before release or PR.", category: "tools", active: true },
  { id: "doc-coauthoring", name: "doc-coauthoring", description: "Guide users through a structured workflow for co-authoring documentation. Use when user wants to write documentation, proposals, technical specs, decision docs, or similar structured content. This wor", category: "tools", active: true },
  { id: "docker-patterns", name: "docker-patterns", description: "Docker and Docker Compose patterns for local development, container security, networking, volume strategies, and multi-service orchestration.", category: "engineering", active: true },
  { id: "docs-cleaner", name: "docs-cleaner", description: "Consolidates redundant documentation while preserving all valuable content. This skill should be used when users want to clean up documentation bloat, merge redundant docs, reduce documentation sprawl", category: "tools", active: true },
  { id: "docx", name: "docx", description: "Use this skill whenever the user wants to create, read, edit, or manipulate Word documents (.docx files). Triggers include: any mention of 'Word doc', 'word document', '.docx', or requests to produce ", category: "tools", active: true },
  { id: "domain-name-brainstormer", name: "domain-name-brainstormer", description: "Generates creative domain name ideas for your project and checks availability across multiple TLDs (.com, .io, .dev, .ai, etc.). Saves hours of brainstorming and manual checking.", category: "tools", active: true },
  { id: "e2e-testing", name: "e2e-testing", description: "Playwright E2E testing patterns, Page Object Model, configuration, CI/CD integration, artifact management, and flaky test strategies.", category: "engineering", active: true },
  { id: "email-sequence", name: "email-sequence", description: "AI skill for email sequence", category: "marketing", active: true },
  { id: "email-template-builder", name: "email-template-builder", description: "AI skill for email template builder", category: "marketing", active: true },
  { id: "energy-procurement", name: "energy-procurement", description: ">", category: "tools", active: true },
  { id: "engineering", name: "engineering-advanced-skills", description: "25 advanced POWERFUL-tier engineering skills covering agent design, RAG architecture, MCP servers, CI/CD pipelines, database design, observability, security auditing, release management, and platform ", category: "tools", active: true },
  { id: "engineering-bundle", name: "engineering-bundle", description: "AI skill for engineering bundle", category: "tools", active: true },
  { id: "engineering-main", name: "engineering-main", description: "AI skill for engineering main", category: "tools", active: true },
  { id: "engineering-team", name: "engineering-skills", description: "23 production-ready engineering skills covering architecture, frontend, backend, fullstack, QA, DevOps, security, AI/ML, data engineering, computer vision, and specialized tools like Playwright Pro, S", category: "tools", active: true },
  { id: "engineering-team-bundle", name: "engineering-team-bundle", description: "AI skill for engineering team bundle", category: "tools", active: true },
  { id: "enterprise-agent-ops", name: "enterprise-agent-ops", description: "Operate long-lived agent workloads with observability, security boundaries, and lifecycle management.", category: "tools", active: true },
  { id: "env-secrets-manager", name: "env-secrets-manager", description: "AI skill for env secrets manager", category: "tools", active: true },
  { id: "epic-design", name: "epic-design", description: ">", category: "product", active: true },
  { id: "eval-harness", name: "eval-harness", description: "Formal evaluation framework for Claude Code sessions implementing eval-driven development (EDD) principles", category: "ai", active: true },
  { id: "excel-automation", name: "excel-automation", description: "Create, parse, and control Excel files on macOS. Professional formatting with openpyxl, complex xlsm parsing with stdlib zipfile+xml for investment bank financial models, and Excel window control via ", category: "tools", active: true },
  { id: "executive-mentor", name: "executive-mentor", description: "AI skill for executive mentor", category: "tools", active: true },
  { id: "experiment-designer", name: "experiment-designer", description: "AI skill for experiment designer", category: "tools", active: true },
  { id: "extract", name: "extract", description: "AI skill for extract", category: "tools", active: true },
  { id: "fact-checker", name: "fact-checker", description: "Verifies factual claims in documents using web search and official sources, then proposes corrections with user confirmation. Use when the user asks to fact-check, verify information, validate claims,", category: "tools", active: true },
  { id: "fda-consultant-specialist", name: "fda-consultant-specialist", description: "AI skill for fda consultant specialist", category: "tools", active: true },
  { id: "file-organizer", name: "file-organizer", description: "Intelligently organizes your files and folders across your computer by understanding context, finding duplicates, suggesting better structures, and automating cleanup tasks. Reduces cognitive load and", category: "productivity", active: true },
  { id: "finance", name: "finance-skills", description: "Production-ready financial analyst skill with ratio analysis, DCF valuation, budget variance analysis, and rolling forecast construction. 4 Python tools (all stdlib-only). Works with Claude Code, Code", category: "tools", active: true },
  { id: "finance-bundle", name: "finance-bundle", description: "AI skill for finance bundle", category: "tools", active: true },
  { id: "financial-analyst", name: "financial-analyst", description: "AI skill for financial analyst", category: "business", active: true },
  { id: "financial-data-collector", name: "financial-data-collector", description: "Collect real financial data for any US publicly traded company from free public sources (yfinance). Output structured JSON consumable by downstream financial skills (DCF modeling, comps analysis, earn", category: "business", active: true },
  { id: "financial-health", name: "financial-health", description: "AI skill for financial health", category: "business", active: true },
  { id: "fix", name: "fix", description: "AI skill for fix", category: "tools", active: true },
  { id: "form-cro", name: "form-cro", description: "AI skill for form cro", category: "marketing", active: true },
  { id: "foundation-models-on-device", name: "foundation-models-on-device", description: "Apple FoundationModels framework for on-device LLM \u2014 text generation, guided generation with @Generable, tool calling, and snapshot streaming in iOS 26+.", category: "tools", active: true },
  { id: "founder-coach", name: "founder-coach", description: "AI skill for founder coach", category: "tools", active: true },
  { id: "free-tool-strategy", name: "free-tool-strategy", description: "AI skill for free tool strategy", category: "business", active: true },
  { id: "frontend-design", name: "frontend-design", description: "Create distinctive, production-grade frontend interfaces with high design quality. Use this skill when the user asks to build web components, pages, or applications. Generates creative, polished code ", category: "engineering", active: true },
  { id: "frontend-patterns", name: "frontend-patterns", description: "Frontend development patterns for React, Next.js, state management, performance optimization, and UI best practices.", category: "engineering", active: true },
  { id: "frontend-slides", name: "frontend-slides", description: "Create stunning, animation-rich HTML presentations from scratch or by converting PowerPoint files. Use when the user wants to build a presentation, convert a PPT/PPTX to web, or create slides for a ta", category: "tools", active: true },
  { id: "gdpr-dsgvo-expert", name: "gdpr-dsgvo-expert", description: "AI skill for gdpr dsgvo expert", category: "tools", active: true },
  { id: "generate", name: "generate", description: "AI skill for generate", category: "tools", active: true },
  { id: "git-worktree-manager", name: "git-worktree-manager", description: "AI skill for git worktree manager", category: "tools", active: true },
  { id: "github-contributor", name: "github-contributor", description: "Strategic guide for becoming an effective GitHub contributor. Covers opportunity discovery, project selection, high-quality PR creation, and reputation building. Use when looking to contribute to open", category: "tools", active: true },
  { id: "github-ops", name: "github-ops", description: "Provides comprehensive GitHub operations using gh CLI and GitHub API. Activates when working with pull requests, issues, repositories, workflows, or GitHub API operations including creating/viewing/me", category: "tools", active: true },
  { id: "goal-tracking", name: "goal-tracking", description: "OKR systems, accountability frameworks, weekly reviews, and $1M roadmap tracking. Turn ambitious goals into daily actions with measurable checkpoints.", category: "productivity", active: true },
  { id: "golang-patterns", name: "golang-patterns", description: "Idiomatic Go patterns, best practices, and conventions for building robust, efficient, and maintainable Go applications.", category: "tools", active: true },
  { id: "golang-testing", name: "golang-testing", description: "Go testing patterns including table-driven tests, subtests, benchmarks, fuzzing, and test coverage. Follows TDD methodology with idiomatic Go practices.", category: "tools", active: true },
  { id: "google-workspace", name: "google-workspace", description: "AI skill for google workspace", category: "tools", active: true },
  { id: "google-workspace-cli", name: "google-workspace-cli", description: "AI skill for google workspace cli", category: "tools", active: true },
  { id: "hard-call", name: "hard-call", description: "AI skill for hard call", category: "tools", active: true },
  { id: "i18n-expert", name: "i18n-expert", description: "This skill should be used when setting up, auditing, or enforcing internationalization/localization in UI codebases (React/TS, i18next or similar, JSON locales), including installing/configuring the i", category: "tools", active: true },
  { id: "iOS-APP-developer", name: "developing-ios-apps", description: "Develops iOS/macOS applications with XcodeGen, SwiftUI, and SPM. Handles Apple Developer signing, notarization, and CI/CD pipelines. Triggers on XcodeGen project.yml, SPM dependency issues, device dep", category: "tools", active: true },
  { id: "image-enhancer", name: "image-enhancer", description: "Improves the quality of images, especially screenshots, by enhancing resolution, sharpness, and clarity. Perfect for preparing images for presentations, documentation, or social media posts.", category: "tools", active: true },
  { id: "incident-commander", name: "incident-commander", description: "AI skill for incident commander", category: "tools", active: true },
  { id: "information-security-manager-iso27001", name: "information-security-manager-iso27001", description: "AI skill for information security manager iso27001", category: "tools", active: true },
  { id: "init", name: "init", description: "AI skill for init", category: "tools", active: true },
  { id: "internal-comms", name: "internal-comms", description: "A set of resources to help me write all kinds of internal communications, using the formats that my company likes to use. Claude should use this skill whenever asked to write some sort of internal com", category: "tools", active: true },
  { id: "internal-narrative", name: "internal-narrative", description: "AI skill for internal narrative", category: "tools", active: true },
  { id: "interview-system-designer", name: "interview-system-designer", description: "AI skill for interview system designer", category: "tools", active: true },
  { id: "intl-expansion", name: "intl-expansion", description: "AI skill for intl expansion", category: "tools", active: true },
  { id: "inventory-demand-planning", name: "inventory-demand-planning", description: ">", category: "tools", active: true },
  { id: "investor-materials", name: "investor-materials", description: "Create and update pitch decks, one-pagers, investor memos, accelerator applications, financial models, and fundraising materials. Use when the user needs investor-facing documents, projections, use-of", category: "business", active: true },
  { id: "investor-outreach", name: "investor-outreach", description: "Draft cold emails, warm intro blurbs, follow-ups, update emails, and investor communications for fundraising. Use when the user wants outreach to angels, VCs, strategic investors, or accelerators and ", category: "business", active: true },
  { id: "invoice-organizer", name: "invoice-organizer", description: "Automatically organizes invoices and receipts for tax preparation by reading messy files, extracting key information, renaming them consistently, and sorting them into logical folders. Turns hours of ", category: "productivity", active: true },
  { id: "isms-audit-expert", name: "isms-audit-expert", description: "AI skill for isms audit expert", category: "tools", active: true },
  { id: "iterative-retrieval", name: "iterative-retrieval", description: "Pattern for progressively refining context retrieval to solve the subagent context problem", category: "tools", active: true },
  { id: "java-coding-standards", name: "java-coding-standards", description: "Java coding standards for Spring Boot services: naming, immutability, Optional usage, streams, exceptions, generics, and project layout.", category: "tools", active: true },
  { id: "jira-expert", name: "jira-expert", description: "AI skill for jira expert", category: "tools", active: true },
  { id: "jpa-patterns", name: "jpa-patterns", description: "JPA/Hibernate patterns for entity design, relationships, query optimization, transactions, auditing, indexing, pagination, and pooling in Spring Boot.", category: "tools", active: true },
  { id: "kotlin-coroutines-flows", name: "kotlin-coroutines-flows", description: "Kotlin Coroutines and Flow patterns for Android and KMP \u2014 structured concurrency, Flow operators, StateFlow, error handling, and testing.", category: "tools", active: true },
  { id: "landing-page-generator", name: "landing-page-generator", description: "AI skill for landing page generator", category: "marketing", active: true },
  { id: "langsmith-fetch", name: "langsmith-fetch", description: "Debug LangChain and LangGraph agents by fetching execution traces from LangSmith Studio. Use when debugging agent behavior, investigating errors, analyzing tool calls, checking memory operations, or e", category: "tools", active: true },
  { id: "launch-strategy", name: "launch-strategy", description: "AI skill for launch strategy", category: "business", active: true },
  { id: "lead-research-assistant", name: "lead-research-assistant", description: "Identifies high-quality leads for your product or service by analyzing your business, searching for target companies, and providing actionable contact strategies. Perfect for sales, business developme", category: "marketing", active: true },
  { id: "liquid-glass-design", name: "liquid-glass-design", description: "iOS 26 Liquid Glass design system \u2014 dynamic glass material with blur, reflection, and interactive morphing for SwiftUI, UIKit, and WidgetKit.", category: "tools", active: true },
  { id: "llm-icon-finder", name: "llm-icon-finder", description: "Finding and accessing AI/LLM model brand icons from lobe-icons library. Use when users need icon URLs, want to download brand logos for AI models/providers/applications (Claude, GPT, Gemini, etc.), or", category: "tools", active: true },
  { id: "logistics-exception-management", name: "logistics-exception-management", description: ">", category: "tools", active: true },
  { id: "loop", name: "loop", description: "AI skill for loop", category: "tools", active: true },
  { id: "ma-playbook", name: "ma-playbook", description: "AI skill for ma playbook", category: "business", active: true },
  { id: "macos-cleaner", name: "macos-cleaner", description: "Analyze and reclaim macOS disk space through intelligent cleanup recommendations. This skill should be used when users report disk space issues, need to clean up their Mac, or want to understand what'", category: "tools", active: true },
  { id: "markdown-tools", name: "markdown-tools", description: "Converts documents to markdown with multi-tool orchestration for best quality. Supports Quick Mode (fast, single tool) and Heavy Mode (best quality, multi-tool merge). Use when converting PDF/DOCX/PPT", category: "tools", active: true },
  { id: "market-research", name: "market-research", description: "Conduct market research, competitive analysis, investor due diligence, and industry intelligence with source attribution and decision-oriented summaries. Use when the user wants market sizing, competi", category: "tools", active: true },
  { id: "marketing-bundle", name: "marketing-bundle", description: "AI skill for marketing bundle", category: "marketing", active: true },
  { id: "marketing-context", name: "marketing-context", description: "AI skill for marketing context", category: "marketing", active: true },
  { id: "marketing-demand-acquisition", name: "marketing-demand-acquisition", description: "AI skill for marketing demand acquisition", category: "marketing", active: true },
  { id: "marketing-ideas", name: "marketing-ideas", description: "AI skill for marketing ideas", category: "marketing", active: true },
  { id: "marketing-ops", name: "marketing-ops", description: "AI skill for marketing ops", category: "marketing", active: true },
  { id: "marketing-psychology", name: "marketing-psychology", description: "AI skill for marketing psychology", category: "marketing", active: true },
  { id: "marketing-skill", name: "marketing-skills", description: "42-skill marketing division for AI coding agents. 7 specialist pods covering content, SEO, CRO, channels, growth, intelligence, and sales. Foundation context system + orchestration router. 27 Python t", category: "marketing", active: true },
  { id: "marketing-skill-bundle", name: "marketing-skill-bundle", description: "AI skill for marketing skill bundle", category: "tools", active: true },
  { id: "marketing-strategy-pmm", name: "marketing-strategy-pmm", description: "AI skill for marketing strategy pmm", category: "marketing", active: true },
  { id: "mcp-builder", name: "mcp-builder", description: "Guide for creating high-quality MCP (Model Context Protocol) servers that enable LLMs to interact with external services through well-designed tools. Use when building MCP servers to integrate externa", category: "ai", active: true },
  { id: "mcp-server-builder", name: "mcp-server-builder", description: "AI skill for mcp server builder", category: "ai", active: true },
  { id: "mdr-745-specialist", name: "mdr-745-specialist", description: "AI skill for mdr 745 specialist", category: "tools", active: true },
  { id: "meeting-insights-analyzer", name: "meeting-insights-analyzer", description: "Analyzes meeting transcripts and recordings to uncover behavioral patterns, communication insights, and actionable feedback. Identifies when you avoid conflict, use filler words, dominate conversation", category: "productivity", active: true },
  { id: "meeting-minutes-taker", name: "meeting-minutes-taker", description: "|", category: "productivity", active: true },
  { id: "mermaid-tools", name: "mermaid-tools", description: "Extracts Mermaid diagrams from markdown files and generates high-quality PNG images using bundled scripts. Activates when working with Mermaid diagrams, converting diagrams to PNG, extracting diagrams", category: "tools", active: true },
  { id: "migrate", name: "migrate", description: "AI skill for migrate", category: "tools", active: true },
  { id: "migration-architect", name: "migration-architect", description: "AI skill for migration architect", category: "tools", active: true },
  { id: "monorepo-navigator", name: "monorepo-navigator", description: "AI skill for monorepo navigator", category: "tools", active: true },
  { id: "ms365-tenant-manager", name: "ms365-tenant-manager", description: "AI skill for ms365 tenant manager", category: "tools", active: true },
  { id: "n8n-workflows", name: "n8n-workflows", description: "Build production n8n workflows \u2014 nodes, expressions, webhooks, error handling, and multi-step automations. The backbone of FlipzyX AI automation delivery.", category: "tools", active: true },
  { id: "nanoclaw-repl", name: "nanoclaw-repl", description: "Operate and extend NanoClaw v2, ECC's zero-dependency session-aware REPL built on claude -p.", category: "tools", active: true },
  { id: "news-intelligence", name: "news-intelligence", description: "Real-time news monitoring, trend analysis, market signals, and AI/tech industry intelligence. Surfaces what matters for FlipzyX and Empire Blueprint decisions.", category: "ai", active: true },
  { id: "nutrient-document-processing", name: "nutrient-document-processing", description: "Process, convert, OCR, extract, redact, sign, and fill documents using the Nutrient DWS API. Works with PDFs, DOCX, XLSX, PPTX, HTML, and images.", category: "tools", active: true },
  { id: "observability-designer", name: "observability-designer", description: "AI skill for observability designer", category: "tools", active: true },
  { id: "okr", name: "okr", description: "AI skill for okr", category: "productivity", active: true },
  { id: "onboarding-cro", name: "onboarding-cro", description: "AI skill for onboarding cro", category: "marketing", active: true },
  { id: "org-health-diagnostic", name: "org-health-diagnostic", description: "AI skill for org health diagnostic", category: "tools", active: true },
  { id: "page-cro", name: "page-cro", description: "AI skill for page cro", category: "marketing", active: true },
  { id: "paid-ads", name: "paid-ads", description: "AI skill for paid ads", category: "marketing", active: true },
  { id: "paywall-upgrade-cro", name: "paywall-upgrade-cro", description: "AI skill for paywall upgrade cro", category: "marketing", active: true },
  { id: "pdf", name: "pdf", description: "Use this skill whenever the user wants to do anything with PDF files. This includes reading or extracting text/tables from PDFs, combining or merging multiple PDFs into one, splitting PDFs apart, rota", category: "tools", active: true },
  { id: "pdf-creator", name: "pdf-creator", description: "Create PDF documents from markdown with proper Chinese font support using weasyprint. This skill should be used when converting markdown to PDF, generating formal documents (legal, trademark filings, ", category: "tools", active: true },
  { id: "performance-profiler", name: "performance-profiler", description: "AI skill for performance profiler", category: "engineering", active: true },
  { id: "perl-patterns", name: "perl-patterns", description: "Modern Perl 5.36+ idioms, best practices, and conventions for building robust, maintainable Perl applications.", category: "tools", active: true },
  { id: "perl-security", name: "perl-security", description: "Comprehensive Perl security covering taint mode, input validation, safe process execution, DBI parameterized queries, web security (XSS/SQLi/CSRF), and perlcritic security policies.", category: "tools", active: true },
  { id: "perl-testing", name: "perl-testing", description: "Perl testing patterns using Test2::V0, Test::More, prove runner, mocking, coverage with Devel::Cover, and TDD methodology.", category: "tools", active: true },
  { id: "persona", name: "persona", description: "AI skill for persona", category: "tools", active: true },
  { id: "pipeline", name: "pipeline", description: "AI skill for pipeline", category: "tools", active: true },
  { id: "plankton-code-quality", name: "plankton-code-quality", description: "Write-time code quality enforcement using Plankton \u2014 auto-formatting, linting, and Claude-powered fixes on every file edit via hooks.", category: "tools", active: true },
  { id: "playwright-pro", name: "playwright-pro", description: "AI skill for playwright pro", category: "tools", active: true },
  { id: "popup-cro", name: "popup-cro", description: "AI skill for popup cro", category: "marketing", active: true },
  { id: "postgres-patterns", name: "postgres-patterns", description: "PostgreSQL database patterns for query optimization, schema design, indexing, and security. Based on Supabase best practices.", category: "tools", active: true },
  { id: "postmortem", name: "postmortem", description: "AI skill for postmortem", category: "productivity", active: true },
  { id: "ppt-creator", name: "ppt-creator", description: "Create professional slide decks from topics or documents. Generates structured content with data-driven charts, speaker notes, and complete PPTX files. Applies persuasive storytelling principles (Pyra", category: "tools", active: true },
  { id: "pptx", name: "pptx", description: "Use this skill any time a .pptx file is involved in any way \u2014 as input, output, or both. This includes: creating slide decks, pitch decks, or presentations; reading, parsing, or extracting text from a", category: "tools", active: true },
  { id: "pr-review-expert", name: "pr-review-expert", description: "AI skill for pr review expert", category: "tools", active: true },
  { id: "prd", name: "prd", description: "AI skill for prd", category: "product", active: true },
  { id: "pricing-strategy", name: "pricing-strategy", description: "AI skill for pricing strategy", category: "business", active: true },
  { id: "product-analysis", name: "product-analysis", description: "Multi-path parallel product analysis with cross-model test-time compute scaling. Spawns parallel agents (Claude Code agent teams + Codex CLI) to explore product from multiple perspectives, then synthe", category: "product", active: true },
  { id: "product-analytics", name: "product-analytics", description: "AI skill for product analytics", category: "product", active: true },
  { id: "product-bundle", name: "product-bundle", description: "AI skill for product bundle", category: "tools", active: true },
  { id: "product-discovery", name: "product-discovery", description: "AI skill for product discovery", category: "product", active: true },
  { id: "product-manager-toolkit", name: "product-manager-toolkit", description: "AI skill for product manager toolkit", category: "product", active: true },
  { id: "product-strategist", name: "product-strategist", description: "AI skill for product strategist", category: "product", active: true },
  { id: "product-team", name: "product-skills", description: "8 production-ready product skills: product manager toolkit with RICE prioritization, agile product owner, product strategist with OKR cascades, UX researcher, UI design system, competitive teardown, l", category: "tools", active: true },
  { id: "product-team-bundle", name: "product-team-bundle", description: "AI skill for product team bundle", category: "tools", active: true },
  { id: "production-scheduling", name: "production-scheduling", description: ">", category: "tools", active: true },
  { id: "programmatic-seo", name: "programmatic-seo", description: "AI skill for programmatic seo", category: "marketing", active: true },
  { id: "project-guidelines-example", name: "project-guidelines-example", description: "Example project-specific skill template based on a real production application.", category: "tools", active: true },
  { id: "project-health", name: "project-health", description: "AI skill for project health", category: "tools", active: true },
  { id: "project-management", name: "pm-skills", description: "6 production-ready project management skills for Atlassian users: senior PM with portfolio management, scrum master with velocity forecasting, Jira expert with JQL mastery, Confluence expert, Atlassia", category: "productivity", active: true },
  { id: "project-management-bundle", name: "project-management-bundle", description: "AI skill for project management bundle", category: "tools", active: true },
  { id: "promote", name: "promote", description: "AI skill for promote", category: "tools", active: true },
  { id: "prompt-engineer-toolkit", name: "prompt-engineer-toolkit", description: "AI skill for prompt engineer toolkit", category: "ai", active: true },
  { id: "prompt-engineering", name: "prompt-engineering", description: "Advanced prompting techniques \u2014 chain-of-thought, few-shot, system prompts, multi-agent orchestration, and cost optimization. Get 10x better AI outputs.", category: "ai", active: true },
  { id: "prompt-optimizer", name: "prompt-optimizer", description: "Transform vague prompts into precise, well-structured specifications using EARS (Easy Approach to Requirements Syntax) methodology. This skill should be used when users provide loose requirements, amb", category: "ai", active: true },
  { id: "promptfoo-evaluation", name: "promptfoo-evaluation", description: "Configures and runs LLM evaluation using Promptfoo framework. Use when setting up prompt testing, creating evaluation configs (promptfooconfig.yaml), writing Python custom assertions, implementing llm", category: "tools", active: true },
  { id: "proposal-generator", name: "proposal-generator", description: "Generate professional proposals, scopes of work, contracts, and invoices for FlipzyX AI automation clients. Close deals faster with polished documents.", category: "business", active: true },
  { id: "python-patterns", name: "python-patterns", description: "Pythonic idioms, PEP 8 standards, type hints, and best practices for building robust, efficient, and maintainable Python applications.", category: "tools", active: true },
  { id: "python-testing", name: "python-testing", description: "Python testing strategies using pytest, TDD methodology, fixtures, mocking, parametrization, and coverage requirements.", category: "tools", active: true },
  { id: "qa-expert", name: "qa-expert", description: "This skill should be used when establishing comprehensive QA testing processes for any software project. Use when creating test strategies, writing test cases following Google Testing Standards, execu", category: "tools", active: true },
  { id: "qms-audit-expert", name: "qms-audit-expert", description: "AI skill for qms audit expert", category: "tools", active: true },
  { id: "quality-documentation-manager", name: "quality-documentation-manager", description: "AI skill for quality documentation manager", category: "tools", active: true },
  { id: "quality-manager-qmr", name: "quality-manager-qmr", description: "AI skill for quality manager qmr", category: "tools", active: true },
  { id: "quality-manager-qms-iso13485", name: "quality-manager-qms-iso13485", description: "AI skill for quality manager qms iso13485", category: "tools", active: true },
  { id: "quality-nonconformance", name: "quality-nonconformance", description: ">", category: "tools", active: true },
  { id: "ra-qm-team", name: "ra-qm-skills", description: "12 production-ready regulatory affairs and quality management skills for HealthTech/MedTech: ISO 13485 QMS, MDR 2017/745, FDA 510(k)/PMA, ISO 27001 ISMS, GDPR/DSGVO compliance, risk management (ISO 14", category: "tools", active: true },
  { id: "ra-qm-team-bundle", name: "ra-qm-team-bundle", description: "AI skill for ra qm team bundle", category: "tools", active: true },
  { id: "ra-qm-team-main", name: "ra-qm-team-main", description: "AI skill for ra qm team main", category: "tools", active: true },
  { id: "raffle-winner-picker", name: "raffle-winner-picker", description: "Picks random winners from lists, spreadsheets, or Google Sheets for giveaways, raffles, and contests. Ensures fair, unbiased selection with transparency.", category: "tools", active: true },
  { id: "rag-architect", name: "rag-architect", description: "AI skill for rag architect", category: "ai", active: true },
  { id: "ralph-loop", name: "ralph-loop", description: ">", category: "tools", active: true },
  { id: "ralphinho-rfc-pipeline", name: "ralphinho-rfc-pipeline", description: "RFC-driven multi-agent DAG execution pattern with quality gates, merge queues, and work unit orchestration.", category: "tools", active: true },
  { id: "referral-program", name: "referral-program", description: "AI skill for referral program", category: "business", active: true },
  { id: "regex-vs-llm-structured-text", name: "regex-vs-llm-structured-text", description: "Decision framework for choosing between regex and LLM when parsing structured text \u2014 start with regex, add LLM only for low-confidence edge cases.", category: "tools", active: true },
  { id: "regulatory-affairs-head", name: "regulatory-affairs-head", description: "AI skill for regulatory affairs head", category: "tools", active: true },
  { id: "release-manager", name: "release-manager", description: "AI skill for release manager", category: "tools", active: true },
  { id: "remember", name: "remember", description: "AI skill for remember", category: "tools", active: true },
  { id: "repomix-unmixer", name: "repomix-unmixer", description: "Extracts files from repomix-packed repositories, restoring original directory structures from XML/Markdown/JSON formats. Activates when users need to unmix repomix files, extract packed repositories, ", category: "tools", active: true },
  { id: "report", name: "report", description: "AI skill for report", category: "tools", active: true },
  { id: "resume", name: "resume", description: "AI skill for resume", category: "tools", active: true },
  { id: "retro", name: "retro", description: "AI skill for retro", category: "productivity", active: true },
  { id: "returns-reverse-logistics", name: "returns-reverse-logistics", description: ">", category: "tools", active: true },
  { id: "revenue-modeling", name: "revenue-modeling", description: "Revenue projections, pricing strategy, MRR/ARR modeling, and financial forecasting for FlipzyX agency and Empire Blueprint. Road to $1M mapped in numbers.", category: "business", active: true },
  { id: "revenue-operations", name: "revenue-operations", description: "AI skill for revenue operations", category: "business", active: true },
  { id: "review", name: "review", description: "AI skill for review", category: "tools", active: true },
  { id: "rice", name: "rice", description: "AI skill for rice", category: "tools", active: true },
  { id: "risk-management-specialist", name: "risk-management-specialist", description: "AI skill for risk management specialist", category: "tools", active: true },
  { id: "roadmap-communicator", name: "roadmap-communicator", description: "AI skill for roadmap communicator", category: "product", active: true },
  { id: "run", name: "run", description: "AI skill for run", category: "tools", active: true },
  { id: "runbook-generator", name: "runbook-generator", description: "AI skill for runbook generator", category: "tools", active: true },
  { id: "saas-health", name: "saas-health", description: "AI skill for saas health", category: "business", active: true },
  { id: "saas-metrics-coach", name: "saas-metrics-coach", description: "AI skill for saas metrics coach", category: "business", active: true },
  { id: "saas-scaffolder", name: "saas-scaffolder", description: "AI skill for saas scaffolder", category: "tools", active: true },
  { id: "sales-engineer", name: "sales-engineer", description: "AI skill for sales engineer", category: "business", active: true },
  { id: "sample-skill", name: "sample-skill", description: "AI skill for sample skill", category: "tools", active: true },
  { id: "scenario-war-room", name: "scenario-war-room", description: "AI skill for scenario war room", category: "tools", active: true },
  { id: "schema-markup", name: "schema-markup", description: "AI skill for schema markup", category: "tools", active: true },
  { id: "scrum-master", name: "scrum-master", description: "AI skill for scrum master", category: "product", active: true },
  { id: "search-first", name: "search-first", description: "Research-before-coding workflow. Search for existing tools, libraries, and patterns before writing custom code. Invokes the researcher agent.", category: "tools", active: true },
  { id: "security-review", name: "security-review", description: "Use this skill when adding authentication, handling user input, working with secrets, creating API endpoints, or implementing payment/sensitive features. Provides comprehensive security checklist and ", category: "engineering", active: true },
  { id: "security-scan", name: "security-scan", description: "Scan your Claude Code configuration (.claude/ directory) for security vulnerabilities, misconfigurations, and injection risks using AgentShield. Checks CLAUDE.md, settings.json, MCP servers, hooks, an", category: "engineering", active: true },
  { id: "self-improving-agent", name: "self-improving-agent", description: "AI skill for self improving agent", category: "ai", active: true },
  { id: "senior-architect", name: "senior-architect", description: "AI skill for senior architect", category: "engineering", active: true },
  { id: "senior-backend", name: "senior-backend", description: "AI skill for senior backend", category: "engineering", active: true },
  { id: "senior-computer-vision", name: "senior-computer-vision", description: "AI skill for senior computer vision", category: "tools", active: true },
  { id: "senior-data-engineer", name: "senior-data-engineer", description: "AI skill for senior data engineer", category: "tools", active: true },
  { id: "senior-data-scientist", name: "senior-data-scientist", description: "AI skill for senior data scientist", category: "tools", active: true },
  { id: "senior-devops", name: "senior-devops", description: "AI skill for senior devops", category: "engineering", active: true },
  { id: "senior-frontend", name: "senior-frontend", description: "AI skill for senior frontend", category: "engineering", active: true },
  { id: "senior-fullstack", name: "senior-fullstack", description: "AI skill for senior fullstack", category: "engineering", active: true },
  { id: "senior-ml-engineer", name: "senior-ml-engineer", description: "AI skill for senior ml engineer", category: "tools", active: true },
  { id: "senior-pm", name: "senior-pm", description: "AI skill for senior pm", category: "tools", active: true },
  { id: "senior-prompt-engineer", name: "senior-prompt-engineer", description: "AI skill for senior prompt engineer", category: "tools", active: true },
  { id: "senior-qa", name: "senior-qa", description: "AI skill for senior qa", category: "tools", active: true },
  { id: "senior-secops", name: "senior-secops", description: "AI skill for senior secops", category: "tools", active: true },
  { id: "senior-security", name: "senior-security", description: "AI skill for senior security", category: "tools", active: true },
  { id: "seo-audit", name: "seo-audit", description: "AI skill for seo audit", category: "marketing", active: true },
  { id: "setup", name: "setup", description: "AI skill for setup", category: "tools", active: true },
  { id: "signup-flow-cro", name: "signup-flow-cro", description: "AI skill for signup flow cro", category: "marketing", active: true },
  { id: "site-architecture", name: "site-architecture", description: "AI skill for site architecture", category: "tools", active: true },
  { id: "skill-creator", name: "skill-creator", description: "Guide for creating effective skills. This skill should be used when users want to create a new skill (or update an existing skill) that extends Claude's capabilities with specialized knowledge, workfl", category: "tools", active: true },
  { id: "skill-reviewer", name: "skill-reviewer", description: "Reviews and improves Claude Code skills against official best practices. Supports three modes - self-review (validate your own skills), external review (evaluate others' skills), and auto-PR (fork, im", category: "tools", active: true },
  { id: "skill-security-auditor", name: "skill-security-auditor", description: "AI skill for skill security auditor", category: "tools", active: true },
  { id: "skill-share", name: "skill-share", description: "A skill that creates new Claude skills and automatically shares them on Slack using Rube for seamless team collaboration and skill discovery.", category: "tools", active: true },
  { id: "skill-stocktake", name: "skill-stocktake", description: "Use when auditing Claude skills and commands for quality. Supports Quick Scan (changed skills only) and Full Stocktake modes with sequential subagent batch evaluation.", category: "tools", active: true },
  { id: "skill-tester", name: "skill-tester", description: "AI skill for skill tester", category: "tools", active: true },
  { id: "skills-review", name: "skills-review", description: "AI skill for skills review", category: "tools", active: true },
  { id: "skills-search", name: "skills-search", description: "This skill should be used when users want to search, discover, install, or manage Claude Code skills from the CCPM registry. Triggers include requests like \"find skills for PDF\", \"search for code revi", category: "tools", active: true },
  { id: "skills-status", name: "skills-status", description: "AI skill for skills status", category: "tools", active: true },
  { id: "slack-gif-creator", name: "slack-gif-creator", description: "Toolkit for creating animated GIFs optimized for Slack, with validators for size constraints and composable animation primitives. This skill applies when users request animated GIFs or emoji animation", category: "tools", active: true },
  { id: "social-content", name: "social-content", description: "AI skill for social content", category: "content", active: true },
  { id: "social-media-analyzer", name: "social-media-analyzer", description: "AI skill for social media analyzer", category: "content", active: true },
  { id: "social-media-manager", name: "social-media-manager", description: "AI skill for social media manager", category: "content", active: true },
  { id: "springboot-patterns", name: "springboot-patterns", description: "Spring Boot architecture patterns, REST API design, layered services, data access, caching, async processing, and logging. Use for Java Spring Boot backend work.", category: "tools", active: true },
  { id: "springboot-security", name: "springboot-security", description: "Spring Security best practices for authn/authz, validation, CSRF, secrets, headers, rate limiting, and dependency security in Java Spring Boot services.", category: "tools", active: true },
  { id: "springboot-tdd", name: "springboot-tdd", description: "Test-driven development for Spring Boot using JUnit 5, Mockito, MockMvc, Testcontainers, and JaCoCo. Use when adding features, fixing bugs, or refactoring.", category: "tools", active: true },
  { id: "springboot-verification", name: "springboot-verification", description: "Verification loop for Spring Boot projects: build, static analysis, tests with coverage, security scans, and diff review before release or PR.", category: "tools", active: true },
  { id: "sprint-health", name: "sprint-health", description: "AI skill for sprint health", category: "productivity", active: true },
  { id: "sprint-plan", name: "sprint-plan", description: "AI skill for sprint plan", category: "productivity", active: true },
  { id: "status", name: "status", description: "AI skill for status", category: "tools", active: true },
  { id: "statusline-generator", name: "statusline-generator", description: "Configures and customizes Claude Code statuslines with multi-line layouts, cost tracking via ccusage, git status indicators, and customizable colors. Activates for statusline setup, installation, conf", category: "tools", active: true },
  { id: "strategic-alignment", name: "strategic-alignment", description: "AI skill for strategic alignment", category: "tools", active: true },
  { id: "strategic-compact", name: "strategic-compact", description: "Suggests manual context compaction at logical intervals to preserve context through task phases rather than arbitrary auto-compaction.", category: "tools", active: true },
  { id: "stress-test", name: "stress-test", description: "AI skill for stress test", category: "tools", active: true },
  { id: "stripe-integration-expert", name: "stripe-integration-expert", description: "AI skill for stripe integration expert", category: "tools", active: true },
  { id: "swift-actor-persistence", name: "swift-actor-persistence", description: "Thread-safe data persistence in Swift using actors \u2014 in-memory cache with file-backed storage, eliminating data races by design.", category: "tools", active: true },
  { id: "swift-concurrency-6-2", name: "swift-concurrency-6-2", description: "Swift 6.2 Approachable Concurrency \u2014 single-threaded by default, @concurrent for explicit background offloading, isolated conformances for main actor types.", category: "tools", active: true },
  { id: "swift-protocol-di-testing", name: "swift-protocol-di-testing", description: "Protocol-based dependency injection for testable Swift code \u2014 mock file system, network, and external APIs using focused protocols and Swift Testing.", category: "tools", active: true },
  { id: "swiftui-patterns", name: "swiftui-patterns", description: "SwiftUI architecture patterns, state management with @Observable, view composition, navigation, performance optimization, and modern iOS/macOS UI best practices.", category: "tools", active: true },
  { id: "tailored-resume-generator", name: "tailored-resume-generator", description: "Analyzes job descriptions and generates tailored resumes that highlight relevant experience, skills, and achievements to maximize interview chances", category: "tools", active: true },
  { id: "tdd", name: "tdd", description: "AI skill for tdd", category: "engineering", active: true },
  { id: "tdd-guide", name: "tdd-guide", description: "AI skill for tdd guide", category: "engineering", active: true },
  { id: "tdd-workflow", name: "tdd-workflow", description: "Use this skill when writing new features, fixing bugs, or refactoring code. Enforces test-driven development with 80%+ coverage including unit, integration, and E2E tests.", category: "tools", active: true },
  { id: "teams-channel-post-writer", name: "teams-channel-post-writer", description: "Creates educational Teams channel posts for internal knowledge sharing about Claude Code features, tools, and best practices. Applies when writing posts, announcements, or documentation to teach colle", category: "tools", active: true },
  { id: "tech-debt", name: "tech-debt", description: "AI skill for tech debt", category: "tools", active: true },
  { id: "tech-debt-tracker", name: "tech-debt-tracker", description: "AI skill for tech debt tracker", category: "tools", active: true },
  { id: "tech-stack-evaluator", name: "tech-stack-evaluator", description: "AI skill for tech stack evaluator", category: "tools", active: true },
  { id: "template-skill", name: "template-skill", description: "Replace with description of the skill and when Claude should use it.", category: "tools", active: true },
  { id: "testrail", name: "testrail", description: "AI skill for testrail", category: "tools", active: true },
  { id: "theme-factory", name: "theme-factory", description: "Toolkit for styling artifacts with a theme. These artifacts can be slides, docs, reportings, HTML landing pages, etc. There are 10 pre-set themes with colors/fonts that you can apply to any artifact t", category: "tools", active: true },
  { id: "total-recall", name: "total-recall", description: ">", category: "tools", active: true },
  { id: "transcript-fixer", name: "transcript-fixer", description: "Corrects speech-to-text transcription errors in meeting notes, lectures, and interviews using dictionary rules and AI. Learns patterns to build personalized correction databases. Use when working with", category: "content", active: true },
  { id: "tunnel-doctor", name: "tunnel-doctor", description: "Diagnoses and fixes conflicts between Tailscale and proxy/VPN tools (Shadowrocket, Clash, Surge) on macOS. Covers five conflict layers - (1) route hijacking, (2) HTTP proxy env var interception, (3) s", category: "tools", active: true },
  { id: "twitter-algorithm-optimizer", name: "twitter-algorithm-optimizer", description: "Analyze and optimize tweets for maximum reach using Twitter's open-source algorithm insights. Rewrite and edit user tweets to improve engagement and visibility based on how the recommendation system r", category: "content", active: true },
  { id: "twitter-reader", name: "twitter-reader", description: "Fetch Twitter/X post content by URL using jina.ai API to bypass JavaScript restrictions. Use when Claude needs to retrieve tweet content including author, timestamp, post text, images, and thread repl", category: "content", active: true },
  { id: "ui-design-system", name: "ui-design-system", description: "AI skill for ui design system", category: "tools", active: true },
  { id: "ui-designer", name: "ui-designer", description: "Extract design systems from reference UI images and generate implementation-ready UI design prompts. Use when users provide UI screenshots/mockups and want to create consistent designs, generate desig", category: "tools", active: true },
  { id: "user-story", name: "user-story", description: "AI skill for user story", category: "product", active: true },
  { id: "ux-researcher-designer", name: "ux-researcher-designer", description: "AI skill for ux researcher designer", category: "tools", active: true },
  { id: "verification-loop", name: "verification-loop", description: "A comprehensive verification system for Claude Code sessions.", category: "tools", active: true },
  { id: "video-comparer", name: "video-comparer", description: "This skill should be used when comparing two videos to analyze compression results or quality differences. Generates interactive HTML reports with quality metrics (PSNR, SSIM) and frame-by-frame visua", category: "video", active: true },
  { id: "video-downloader", name: "youtube-downloader", description: "Download YouTube videos with customizable quality and format options. Use this skill when the user asks to download, save, or grab YouTube videos. Supports various quality settings (best, 1080p, 720p,", category: "video", active: true },
  { id: "video-scripting", name: "video-scripting", description: "Write high-converting video scripts for TikTok, YouTube, and Instagram Reels. Storytelling frameworks, pacing, hooks, and CTA patterns that drive watch time and action.", category: "content", active: true },
  { id: "videodb", name: "videodb", description: "See, Understand, Act on video and audio. See- ingest from local files, URLs, RTSP/live feeds, or live record desktop; return realtime context and playable stream links. Understand- extract frames, bui", category: "video", active: true },
  { id: "viral-content", name: "viral-content", description: "Proven viral content formulas for TikTok, Instagram Reels, and LinkedIn. Hook science, retention patterns, and algorithm optimization for maximum reach.", category: "content", active: true },
  { id: "visa-doc-translate", name: "visa-doc-translate", description: "Translate visa application documents (images) to English and create a bilingual PDF with original and translation", category: "tools", active: true },
  { id: "web-artifacts-builder", name: "web-artifacts-builder", description: "Suite of tools for creating elaborate, multi-component claude.ai HTML artifacts using modern frontend web technologies (React, Tailwind CSS, shadcn/ui). Use for complex artifacts requiring state manag", category: "tools", active: true },
  { id: "web-scraping", name: "web-scraping", description: "Extract data from any website using Python (BeautifulSoup, Playwright, httpx), handle pagination, anti-bot measures, and structure data for automations.", category: "tools", active: true },
  { id: "webapp-testing", name: "webapp-testing", description: "Toolkit for interacting with and testing local web applications using Playwright. Supports verifying frontend functionality, debugging UI behavior, capturing browser screenshots, and viewing browser l", category: "engineering", active: true },
  { id: "windows-remote-desktop-connection-doctor", name: "windows-remote-desktop-connection-doctor", description: "Diagnose Windows App (Microsoft Remote Desktop / Azure Virtual Desktop / W365) connection quality issues on macOS. Analyze transport protocol selection (UDP Shortpath vs WebSocket), detect VPN/proxy i", category: "tools", active: true },
  { id: "x-twitter-growth", name: "x-twitter-growth", description: "AI skill for x twitter growth", category: "content", active: true },
  { id: "xlsx", name: "xlsx", description: "Use this skill any time a spreadsheet file is the primary input or output. This means any task where the user wants to: open, read, edit, or fix an existing .xlsx, .xlsm, .csv, or .tsv file (e.g., add", category: "tools", active: true },
  { id: "youtube-downloader", name: "youtube-downloader", description: "Download YouTube videos and HLS streams (m3u8) from platforms like Mux, Vimeo, etc. using yt-dlp and ffmpeg. Use this skill when users request downloading videos, extracting audio, handling protected ", category: "video", active: true },
]

export const SKILL_CATEGORIES: Record<SkillCategory, { label: string; icon: string; color: string }> = {
  empire: { label: 'Empire', icon: '👑', color: 'text-yellow-400' },
  content: { label: 'Content', icon: '✍️', color: 'text-cyan-400' },
  marketing: { label: 'Marketing', icon: '📢', color: 'text-purple-400' },
  business: { label: 'Business', icon: '💼', color: 'text-green-400' },
  engineering: { label: 'Engineering', icon: '⚙️', color: 'text-blue-400' },
  ai: { label: 'AI & Agents', icon: '🤖', color: 'text-pink-400' },
  video: { label: 'Video', icon: '🎬', color: 'text-red-400' },
  productivity: { label: 'Productivity', icon: '⚡', color: 'text-orange-400' },
  product: { label: 'Product', icon: '📦', color: 'text-indigo-400' },
  tools: { label: 'Tools', icon: '🔧', color: 'text-gray-400' },
}

export function findSkill(query: string): Skill | undefined {
  const q = query.toLowerCase().replace(/[^a-z0-9-]/g, " ").trim()
  return SKILLS_REGISTRY.find(s => s.id === q || s.name.toLowerCase().includes(q) || q.includes(s.id))
}

export function searchSkills(query: string): Skill[] {
  if (!query) return SKILLS_REGISTRY
  const q = query.toLowerCase()
  return SKILLS_REGISTRY.filter(s =>
    s.id.includes(q) || s.name.toLowerCase().includes(q) || s.description.toLowerCase().includes(q) || s.category.includes(q)
  )
}